---
title: "HW3"
author: "Vicki Hertzberg"
date: "February 8, 2017"
output: html_document
---



You are now the data slave to the principal investigator Dr. Vinca Monster. Dr. M is in the Grape Program at State U, and you are just a poor graduate student trying to get your degree. Dr. M is interested in wine preferences and the influences of physico-chemical properties on preferences. Her laboratory has gathered an extensive dataset on Portugese white varietals.


You will find the white_wines.csv file and its description in my github repo (https://github.com/vhertzb/Regression-1)[https://github.com/vhertzb/Regression-1].

Please use the techniques you have learned in the last two classes, specifically exploratory data analysis and linear regression, to determine association of the wine properties on preference. 

Prepare a report for presentation at the next Monster lab meeting about this dataset.

Rubric:

Exploration (summary statistics (the m's), univariate graphs, multivariate graphs)
Regression (Models explored, diagnostics completed, final model choice, justification)

Please include a concluding paragraph (or two) about the implications of your findings.